/**
 * Capacidades da locadora — só leitura do cadastro que JÁ existe lá.
 * Fora do pacote "atender": o Conversador não fala com estas tools.
 */
import { declararTools } from "./tipos";

export const TOOLS_LOCADORA = declararTools([
  {
    name: "moope_lookup_locatario",
    category: "read",
    rotulo: "Identificar locatário",
    explicacao:
      "Confere se o telefone, o CPF ou a placa já é cadastro desta locadora. Não cria cliente novo.",
    oQueToca: "Cadastro da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_get_retrato",
    category: "read",
    rotulo: "Ver situação do locatário",
    explicacao:
      "Mostra placa, contrato, atraso, documentos e o link de boleto ou portal que a locadora já tem.",
    oQueToca: "Contrato e cobrança da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_get_atendimento",
    category: "read",
    rotulo: "Menu do WhatsApp",
    explicacao:
      "Busca o menu que a locadora editou no MOOPE (Textos do WhatsApp). O bot manda esse texto na entrada.",
    oQueToca: "Textos da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_listar_oferta",
    category: "read",
    rotulo: "Veículos disponíveis",
    explicacao:
      "Lista a frota da página de ofertas: preço se existir, elétrico, opcionais e tarja ALUGADO. Sem inventar valor ou fechar contrato.",
    oQueToca: "Página de ofertas da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_lookup_investidor",
    category: "read",
    rotulo: "Identificar investidor",
    explicacao: "Confere se o telefone ou o CPF é investidor desta locadora. Não cria cadastro.",
    oQueToca: "Cadastro de investidores",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_get_retrato_investidor",
    category: "read",
    rotulo: "Portal do investidor",
    explicacao: "Link do portal e último período de fechamento. Não envia PDF nem valor inventado.",
    oQueToca: "Portal do investidor",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_cliente",
    category: "read",
    rotulo: "Dados do locatário",
    explicacao: "Mostra nome, status, telefone mascarado, contrato e veículo atual. Nome sozinho não identifica.",
    oQueToca: "Cadastro da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_locacao",
    category: "read",
    rotulo: "Dados da locação",
    explicacao: "Contratos ativos: datas, veículo e status. Sem alterar contrato.",
    oQueToca: "Contrato da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_financeiro",
    category: "read",
    rotulo: "Financeiro",
    explicacao: "Parcelas, vencimentos, atraso e links oficiais já existentes.",
    oQueToca: "Cobrança da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_obter_segunda_via",
    category: "read",
    rotulo: "Segunda via oficial",
    explicacao: "Devolve boleto ou PIX que a gestão já gerou. Não cria cobrança nova.",
    oQueToca: "Boleto e PIX oficiais",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_disponibilidade",
    category: "read",
    rotulo: "Disponibilidade",
    explicacao: "Consulta disponibilidade real por período. Não usa status genérico da frota.",
    oQueToca: "Agenda da frota",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_manutencao",
    category: "read",
    rotulo: "Manutenção",
    explicacao: "Mostra manutenção que pode ser dita ao locatário ou ao atendente.",
    oQueToca: "Manutenção autorizada",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_multas",
    category: "read",
    rotulo: "Multas",
    explicacao: "Multas do cliente ou contrato autorizado: data, resumo, valor e status.",
    oQueToca: "Multas do contrato",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_sinistros",
    category: "read",
    rotulo: "Sinistros",
    explicacao: "Status e informações autorizadas de sinistro. Sem editar.",
    oQueToca: "Sinistros autorizados",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_vistoria",
    category: "read",
    rotulo: "Vistorias",
    explicacao: "Referência autorizada de vistoria ou checklist.",
    oQueToca: "Vistoria autorizada",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_consultar_documentos",
    category: "read",
    rotulo: "Documentos",
    explicacao: "Documentos do locatário identificado. Não envia arquivo de outra pessoa.",
    oQueToca: "Documentos autorizados",
    risco: "seguro",
    pacotes: ["organizar"],
  },
  {
    name: "moope_listar_unidades",
    category: "read",
    rotulo: "Unidades",
    explicacao: "Lista filiais que a gestão realmente tem. Não inventa unidade.",
    oQueToca: "Unidades da locadora",
    risco: "seguro",
    pacotes: ["organizar"],
  },
]);
